services:
    backend:
        build:
            context: ./backend
        container_name: backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend/app:/app/app
        env_file:
            - ./.env.local
        # depends
