"""add deleted_at to products table

Revision ID: 7128c6983ee1
Revises: 32df2d3a58ab
Create Date: 2026-04-21 20:31:34.441275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7128c6983ee1'
down_revision: Union[str, Sequence[str], None] = '32df2d3a58ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_stock_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_stock_history_id'), 'product_stock_history', ['id'], unique=False)
    op.add_column('products', sa.Column('supplier_deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'supplier_deleted_at')
    op.drop_index(op.f('ix_product_stock_history_id'), table_name='product_stock_history')
    op.drop_table('product_stock_history')
    # ### end Alembic commands ###
